name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4.1
  GODOT_MIRROR: https://github.com/godotengine/godot/releases/download
  GODOT_BASE: Godot_v4.4.1-stable_linux.x86_64  # centralized base name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: â¬‡ï¸ Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup symlink for GUT
      run: |
        mkdir -p addons
        ln -sf ../externals/gut/addons/gut addons/gut

    - name: â¬‡ï¸ Download Godot Headless
      run: |
        wget "${{ env.GODOT_MIRROR }}/${{ env.GODOT_VERSION }}-stable/${{ env.GODOT_BASE }}.zip"
        unzip "${{ env.GODOT_BASE }}.zip" -d godot
        chmod +x "godot/${{ env.GODOT_BASE }}"

    - name: Define GODOT binary path
      run: echo "GODOT=./godot/${{ env.GODOT_BASE }}" >> $GITHUB_ENV

    - name: ðŸ”ƒ Preload project (import assets)
      run: timeout 40s $GODOT --headless --import --path . --quit || true # always fails

    - name: âœ… Run GUT tests
      run: $GODOT --headless -s addons/gut/gut_cmdln.gd -gprefix='' -gsuffix='_test.gd' -gdir tests -gexit --verbose

    - name: ðŸ“¢ Notify status changes
      if: always()
      uses: vokimon/gha-notify-telegram@master
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        # the default to false should be more digest
        report_green_to_green: false
